#pragma once

const char* basicShaderVertSrc =
"#version 300 es\n"
"//Basic Vertex Shader\n"
"\n"
"layout(location = 0) in vec4 position;\n"
"layout(location = 1) in vec2 texCoord;\n"
"layout(location = 2) in vec4 color;\n"
"\n"
"out vec2 v_TexCoord;\n"
"out vec4 v_Color;\n"
"\n"
"uniform mat4 u_MVP;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = u_MVP * position;\n"
"    v_TexCoord = texCoord;\n"
"    v_Color = color;\n"
"}\n";

const char* basicShaderFragSrc = 
"#version 300 es\n"
"//Basic Fragment Shader\n"
"\n"
"precision highp float;\n"
"layout(location = 0) out vec4 color;\n"
"\n"
"uniform sampler2D u_Texture;\n"
"\n"
"in vec2 v_TexCoord;\n"
"in vec4 v_Color;\n"
"\n"
"void main()\n"
"{\n"
"    color = texture(u_Texture, v_TexCoord);\n"
"}\n";

const char* tileShaderVertSrc =
"#version 300 es\n"
"//Tile Vertex Shader\n"
"\n"
"layout(location = 0) in vec4 position;\n"
"layout(location = 1) in vec2 texCoord;\n"
"\n"
"out vec2 v_TexCoord;\n"
"\n"
"uniform mat4 u_MVP;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = u_MVP * position;\n"
"    v_TexCoord = texCoord;\n"
"}\n";

const char* tileShaderFragSrc =
"#version 300 es\n"
"//Tile Fragment Shader\n"
"\n"
"precision highp float;\n"
"\n"
"layout(location = 0) out vec4 color;\n"
"\n"
"uniform sampler2D u_Texture;\n"
"\n"
"in vec2 v_TexCoord;\n"
"\n"
"void main()\n"
"{\n"
"    color = texture(u_Texture, v_TexCoord);\n"
"}\n";

const char* frameShaderVertSrc =
"#version 300 es\n"
"//Frame Vertex Shader\n"
"\n"
"layout(location = 0) in vec4 position;\n"
"layout(location = 1) in vec2 texCoord;\n"
"\n"
"out vec2 v_TexCoord;\n"
"\n"
"uniform mat4 u_PROJ;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = position;\n"
"    v_TexCoord = texCoord;\n"
"}\n";

const char* frameShaderFragSrc =
"#version 300 es\n"
"//Frame Fragment Shader\n"
"\n"
"precision highp float;\n"
"\n"
"layout(location = 0) out vec4 color;\n"
"\n"
"uniform sampler2D u_Texture;\n"
"\n"
"in vec2 v_TexCoord;\n"
"\n"
"void main()\n"
"{\n"
"    color = texture(u_Texture, v_TexCoord);\n"
"}\n";